settings:
  username: "ThiagoPanini"
  commit_msg: "âš¡ Update README with the recent activity"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events:
    - "comments"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT-03:00"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_name: "readme-bot"
  commit_email: "panini.development@gmail.com"
  line_prefix: "{NUM}. "
  ignored_repos:
    - ThiagoPanini/ThiagoPanini
messages:
  comments: "ğŸ’¬ Commented on {ID} in {REPO}"
  push: "â¬†ï¸ Realizou o push de {AMOUNT} commit(s) em {REPO}"
  issue_opened: "â—ï¸ Abriu a issue {ID} em {REPO}"
  issue_closed: "âœ”ï¸ Fechou a issue {ID} em {REPO}"
  pr_opened: "ğŸ’ª Abriu o PR {ID} em {REPO}"
  pr_closed: "âŒ Abriu o PR {ID} em {REPO}"
  pr_merged: "ğŸ‰ Realizou o merge do PR {ID} em {REPO}"
  create_repo: "ğŸ“” Criou o novo repositÃ³rio {REPO}"
  fork_repo: "ğŸ”± Forked {FORK} de {REPO}"
  wiki_create: "ğŸ“– Criou uma nova pÃ¡gina wiki {WIKI} em {REPO}"
  added_member: "ğŸ¤ Se tornou colaborador em {REPO}"
  changes_approved: "ğŸ‘ Aprovou {ID} em {REPO}"
  changes_requested: "ğŸ”´ Requisitou mudanÃ§as em {ID} em {REPO}"
  new_release: "âœŒï¸ LanÃ§ou a release {ID} em {REPO}"
  new_star: "â­ Favoritou {REPO}"
