settings:
  username: "ThiagoPanini"
  commit_msg: "ci: updating GitHub profile recent activity"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events:
    - "comments"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT-03:00"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_name: "readme-bot"
  commit_email: "panini.development@gmail.com"
  line_prefix: "{NUM}. "
  ignored_repos:
    - ThiagoPanini/ThiagoPanini
messages:
  comments: "ğŸ’¬ Commented on {ID} in {REPO}"
  push: "â¬†ï¸ Pushed {AMOUNT} commits to {REPO}"
  issue_opened: "â—ï¸ Opened issue {ID} on {REPO}"
  issue_closed: "âœ”ï¸ Closed issue {ID} on {REPO}"
  pr_opened: "ğŸ’ª Opened PR {ID} on {REPO}"
  pr_closed: "âŒ Closed PR {ID} on {REPO}"
  pr_merged: "ğŸ‰ Merged PR {ID} on {REPO}"
  create_repo: "ğŸ“” Created the repo {REPO}"
  fork_repo: "ğŸ”± Forked {FORK} from {REPO}"
  wiki_create: "ğŸ“– Created a wiki page {WIKI} on {REPO}"
  added_member: "ğŸ¤ Collaborated to {REPO}"
  changes_approved: "ğŸ‘ Approved change {ID} on {REPO}"
  changes_requested: "ğŸ”´ Requested changes {ID} on {REPO}"
  new_release: "âœŒï¸ Launched release {ID} on {REPO}"
  new_star: "â­ Gave a stargaze on {REPO}"
