name: Atividade Recente no Github - README

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Atualiza o README com atividade recente

    steps:
      - uses: actions/checkout@v2
      - uses: DenverCoderOne/github-activity-readme@commit-username-and-email
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
